name: EasyTask/Continuous_Integration
on:
  push:
    paths:
    - main
  workflow_dispatch:
    
env:
  BuildConfiguration: release
  BuildPlatform: any cpu
  system_debug: 'false'
jobs:
  Phase_1:
    name: Agent job 1
    runs-on: windows-2022
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: NuGet restore CommonLib
      run: nuget restore CommonLib/CommonLib.sln -Verbosity Detailed
    - name: NuGet restore EasyTaskAddin
      run: nuget restore EasyTask/EasyTaskAddin.sln -Verbosity Detailed
    - name: install msbuild
      uses: microsoft/setup-msbuild@v2
    - name: run msbuild
      run: msbuild EasyTask/EasyTaskAddin.sln -p:Configuration=${{ env.BuildConfiguration }} -p:Platform="${{ env.BuildPlatform }}" -v:normal
    - name: 'Publish Artifact: drop'
      uses: actions/upload-artifact@v4.1.0
      with:
        name: EasyTask${{ github.run_id }}
        if-no-files-found: error
        path: "**\\*\\*.msi"
